### ISSUE TITLE
Schematic Viewer used directly renders upside down

### ISSUE THREAD

**Issue by KorvinSzanto** [tscircuit/tscircuit#121]
I believe this is likely related to #120 and I'm not sure whether it's intended that positive Y goes up or down.

Compare the directly used `Schematic` component to `tsci dev`:

### Direct `<Schematic/>` usage
![image](https://github.com/tscircuit/tscircuit/assets/1007419/948c6b16-3134-4ab4-8379-7f98b144c045)

### `tsci dev`
![image](https://github.com/tscircuit/tscircuit/assets/1007419/02b62e88-4f50-4794-8af4-56a5dc6acfa2)

Thankfully the icons and text are also upside down so it's still accurate, just odd behavior when manually organizing a schematic with `sch_x` and `sch_y`.

**Comment by seveibar** [comment]
I think this should be fixed now with @tscircuit/schematic-viewer@1.2.4 and @tscircuit/builder@1.5.88. Note that the builder is a peer dependency of the schematic-viewer. If you're still hitting it let me know. I usually create reproductions for issues inside the Storybook of the [schematic viewer](https://github.com/tscircuit/schematic-viewer) (just by running `npm run start`) but I see the bugs are rendering properly there at the moment so it might have been fixed.

![image](https://github.com/tscircuit/tscircuit/assets/1910070/a6c7d33a-2892-4947-b05c-8abab25e3e31)
