### ISSUE TITLE
Modify the "soup" specification to add Oval/Pill support

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#208]
We'll need to support "circle" (default) and "oval", also probably pill as shown in #205 

![image](https://github.com/tscircuit/tscircuit/assets/1910070/1d26e609-8064-4342-868c-c281898773e7)

This is the repo where the specification can be modified https://github.com/tscircuit/soup

**Comment by imrishabh18** [comment]
Hey @seveibar! 👋 I would like to work on this.

**Comment by seveibar** [comment]
Thanks to @imrishabh18 we now have support for Ovals, but we're still missing support for Pills, I'm going to edit the issue title to reflect that we only need "Pill" support now.

RE: Pills vs ovals

![image](https://github.com/tscircuit/tscircuit/assets/1910070/1e62f6c1-7c7a-4783-ba66-0543ededd6cc)

![image](https://github.com/tscircuit/tscircuit/assets/1910070/fc9d0474-92c7-4118-bb1d-2335cdaa6a30)

**Comment by seveibar** [comment]
Looking into this more, I think our definition of Oval _might_ cover creating pills. I'm going to close for now.

**Comment by seveibar** [comment]
Ah no we do need 2 different shapes, but the parameters outer/inner width/height i _think_ would be the same, the drawing function would just change based on the shape being used.

**Comment by imrishabh18** [comment]
Where is the drawing function located, can you please point me to that?

**Comment by seveibar** [comment]
@imrishabh18 this video should help!


https://github.com/tscircuit/tscircuit/assets/1910070/64c4c3c8-03e8-4ee1-ae96-5371dac93d0d
