### ISSUE TITLE
Show the current package name in `tsci dev`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#210]
Right now it's showing placeholder text "@seveibar/arduino@1.0.0", it should display the name of the current package being developed.

![image](https://github.com/tscircuit/tscircuit/assets/1910070/0f6c245e-384c-4f0d-af23-18b8e9849ceb)

Fix is likely inside the [tscircuit/cli](https://github.com/tscircuit/cli) repo

![image](https://github.com/tscircuit/tscircuit/assets/1910070/2eab4001-9dbc-4112-9910-6bd653c9bfb6)

**Comment by imrishabh18** [comment]
@seveibar Isn't the expected behaviour already present? I can see the package name being seen.
<img width="1753" alt="Screenshot 2024-07-18 at 9 04 53 PM" src="https://github.com/user-attachments/assets/eed11e46-c86b-42ec-8263-3b8cf5d50f5d">

**Comment by seveibar** [comment]
Yes someone fixed it already!
