### ISSUE TITLE
bad overlap on `tsci dev` overlay when exporting

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#212]
![image](https://github.com/tscircuit/tscircuit/assets/1910070/6ba73d34-e86a-482a-82fe-b66992078a41)

Fix will be in [tscircuit/cli](https://github.com/tscircuit/cli) inside the frontend directory

**Comment by sahilahluwalia** [comment]
![image](https://github.com/tscircuit/tscircuit/assets/44433679/2b28677a-2960-4dc7-9600-3e371a08b229)
I am a bit clueless about what needs to be done.

edit-1 
![image](https://github.com/tscircuit/tscircuit/assets/44433679/c91a0ced-d43b-4d0a-8417-ae566c78f436)
this?

**Comment by imrishabh18** [comment]
Hey @sahilahluwalia, for this issue you need to make sure that the export dialog is always on top, and not covered by the canvas components.
