### ISSUE TITLE
Pills not converted properly in kicad file conversion

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#215]
- [x] Update https://github.com/tscircuit/kicad-mod-converter to support outputting "pills" for some kicad shapes
- [x] Update https://github.com/tscircuit/pcb-viewer to support rendering pills
- [x] Update https://github.com/tscircuit/kicad-viewer dependencies to fix conversion & pcb-viewer

![image](https://github.com/tscircuit/tscircuit/assets/1910070/5d6fc8ec-9bee-4201-9b6f-7a0322ee6444)

**Comment by imrishabh18** [comment]
Before
![Screenshot 2024-07-02 at 2 53 10 AM](https://github.com/tscircuit/tscircuit/assets/38923768/b1269158-d2ba-46ea-8586-e5dbef7a722f)

After
![Screenshot 2024-07-02 at 2 23 08 AM](https://github.com/tscircuit/tscircuit/assets/38923768/25101b70-67ae-467f-af03-46f6f5ce7de3)

**Comment by seveibar** [comment]
From the image above, that's still not quite correct, the kicad version is actually a pill not an oval

**Comment by imrishabh18** [comment]
Yeah, I will add the pill shape now. Just wanted to do an oval first, will add the pill shape after this

**Comment by imrishabh18** [comment]
<img width="832" alt="Screenshot 2024-07-04 at 1 56 13 AM" src="https://github.com/tscircuit/tscircuit/assets/38923768/7447d737-6528-4038-94c6-d421ab8cdd94">

**Comment by seveibar** [comment]
@imrishabh18 that's amazing!!!!
