### ISSUE TITLE
Schematic Ports should be an obstacle/a bigger obstacle when schematic autorouting

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#250]
To prevent issues like this:

![image](https://github.com/user-attachments/assets/6cfad024-bce5-4703-92cc-55be1be12810)

**Comment by seveibar** [comment]
CC @imrishabh18 knows about this stuff 😁

**Comment by imrishabh18** [comment]
Taking this up!

**Comment by imrishabh18** [comment]
@seveibar Can you share the circuit please for this? It would be really helpful

**Comment by imrishabh18** [comment]
@seveibar  I think we can close this, I was trying to reproduce this but it seems like it's fixed!

<img width="940" alt="Screenshot 2024-08-03 at 3 30 20 PM" src="https://github.com/user-attachments/assets/839ff973-35e5-40bc-b1ff-e9e8d2d5ea1c">

**Comment by seveibar** [comment]
@imrishabh18 nice!
