### ISSUE TITLE
When a component is on the bottom layer, flip the 3d model upside down

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#258]
# Currently what happens (WRONG: component is not pointing the right way! It's pointing upwards rather than downwards)

![image](https://github.com/user-attachments/assets/394c3556-feb9-4022-baf9-8e205251b6fa)

# What's supposed to happen (CORRECT, there is some of the component on the top, but it's mostly on the bottom and it's facing downwards)

![image](https://github.com/user-attachments/assets/4c43173d-f000-4d8c-bc45-a44623e63ff2)

![image](https://github.com/user-attachments/assets/27633601-baa2-4656-9e90-0aad222ee9e6)

# How to fix

- [ ] Write a test with a component with a `cadModel` defined and put the component on the bottom layer (in the builder repo)
   - [ ] You can use this as the `objUrl` for the `cadModel` (it's the model above) `"https://modelcdn.tscircuit.com/easyeda_models/download?uuid=6331f645d89e4b919bdba0cb4f3544ce&pn=C124379"`
- [ ] Look for where the `cad_component` is created inside of `ComponentBuilder`, it should have `rotation.y` set to `180` when it's on the bottom layer
- [ ] Use the debug server and `logSoup` to make sure it flips properly

**Comment by seveibar** [comment]
@Slaviiiii are you still working on this? If not can you unassign yourself

**Comment by Slaviiiii** [comment]
I could not understand what the problem was with it

**Comment by Slaviiiii** [comment]
I can reassign if I understand how the codebase works further in
