### ISSUE TITLE
Support for displaying Manufacturer Part Number on tscircuit

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#262]
- [x] Add `manufacturer_part_number` to `source_component` via https://github.com/tscircuit/soup
- [x] Add `manufacturerPartNumber` to `<bug />` via https://github.com/tscircuit/props
- [x] Add support for rendering the manufacturer part number below the box in [schematic-viewer](https://github.com/tscircuit/schematic-viewer) (as shown below in a PDF from a different tool)

![image](https://github.com/user-attachments/assets/eebe9148-bf3d-4d63-8574-4ce01088200e)

**Comment by seveibar** [comment]
CC @imrishabh18 i think this would have been pretty helpful, we discussed how this would improve schematic reviews a bit in slack

**Comment by imrishabh18** [comment]
Yeah, It would really helpful. Taking a look at this
