### ISSUE TITLE
Configurable trace widths for nets

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#264]
For my motor controller board, my trace widths are super thin but some of these traces must carry a lot of power. We need to allow nets to have configurable trace widths via

```tsx
<net traceWidth="0.5mm" />
```

Also:

```tsx
<net minTraceWidth="0.25mm" maxTraceWidth="0.75mm" />
```

- [x] Add prop for `traceWidth` in tscircuit/props
- [ ] Support reading prop in builder and applying the prop to nets

![image](https://github.com/user-attachments/assets/f93a1298-c536-4d49-93f7-b7277102b56e)

**Comment by imrishabh18** [comment]
@seveibar For this, shouldn't we just have `traceWidth` prop? How to decide between the range of `minTraceWidth`  and `maxTraceWidth` which thickness to choose.

**Comment by seveibar** [comment]
@imrishabh18 sometimes the traceWidth needs to automatically expand to be as large as possible whenever possible. For this we need to use a "trace expansion algorithm". Most power traces we want to be very wide, but will need to become narrow to fit into or through certain parts of the circuit.

We don't currently have a trace expansion algorithm although I'm very close to one, might have it finished this week.

We don't need the algorithm if we support a ui to edit trace width inside of hints, to do this we would first need to add traceWidth to the <tracehint /> component

The pcb-viewer probably doesn't support varying the width right now, also i doubt some of our checks support it. Nonetheless it's pretty important for routing power automatically.

**Comment by imrishabh18** [comment]
I see, so I will just start with the `traceWidth` right now. I think after your work on the algo is done, probably we can then check the min and max thing

**Comment by seveibar** [comment]
@imrishabh18 fwiw its ok to implement parts of this w/o the algorithm or ui etc. we just have to take baby steps haha

**Comment by seveibar** [comment]
We want to support something like this:

Some custom trace width in a trace hint...

`<tracehint x={0} y={0} traceWidth="5mm" />`

Then that should output in the PCB viewer a line like this:

![image](https://github.com/user-attachments/assets/5eb10c49-b3fd-4ce4-b73b-ae177ce598ac)

![image](https://github.com/user-attachments/assets/439bca6a-3a07-4be4-98a8-4f1af5310716)
