### ISSUE TITLE
Highlight other connected pads/traces when you hover over a pad

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#268]
This allows you to see pads and traces that should be connected

![image](https://github.com/user-attachments/assets/41b89d15-ef33-48d4-a9d8-f43fe1f74fc5)

**Comment by ShiboSoftwareDev** [comment]
![image](https://github.com/user-attachments/assets/3a2e3730-08aa-4790-b4ec-3066a64c4f24)
I just started working on this but why is the trace not showing in the pcb-viewer tests?

**Comment by ShiboSoftwareDev** [comment]
and is there a specific behavior you expect, or just normal selection but for all connected pads/traces? @seveibar

**Comment by seveibar** [comment]
@ShiboSoftwareDev it might have been broken by recent updates to the trace renderer (CC @imrishabh18) it's an issue that we should fix.

@ShiboSoftwareDev hovering over a pad should change _the color of the pad_ to white, and all other connected pads/traces should also change to white. I don't think we should pop up the squares.

**Comment by ShiboSoftwareDev** [comment]
![image](https://github.com/user-attachments/assets/47135484-2cd2-4b22-833c-bcdb6cd16b27)
![image](https://github.com/user-attachments/assets/c54fe7f5-9751-4eb5-90eb-65512a2161d8)
@seveibar how is it looking so far?

**Comment by seveibar** [comment]
@ShiboSoftwareDev thats great
