### ISSUE TITLE
Rename `<bug />` to `<chip />`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#286]
I will forever wonder why it took me so long to consider this alternate name. We should accept both names for a while and eventually deprecate `<bug />`

- [x] Change name of props definitions in [@tscircuit/props](https://github.com/tscircuit/props)
- [x] Make [tscircuit/react-fiber](https://github.com/tscircuit/react-fiber) translate chip into bug
- [x] Introduce `simple_chip` type into [tscircuit/soup](https://github.com/tscircuit/soup)

**Comment by abhijitxy** [comment]
I’d like to work on this please assign me seve:)
