### ISSUE TITLE
Builder sometimes outputs duplicate items in the `port_hints` array

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#289]
This issue is for [tscircuit/builder](https://github.com/tscircuit/builder)

- [ ] Create a test that replicates the issue. You should be able to do this just by creating a test that makes a `chip` (`bug`) with `footprint="soic8"`, then build the soup. Use the standard [test pattern](https://github.com/tscircuit/builder/blob/main/DEVELOPMENT.md)
- [ ] Use `su(soup).source_port.list()` and ensure that no source ports have a duplicate inside of `port_hints`
- [ ] If they do, try to debug the error. This could be tricky because the builder is hard to understand, but the most likely cause is inside `FootprintBuilder`

![image](https://github.com/user-attachments/assets/7e315356-f1ec-400d-bc7f-f4ca83dbf712)

**Comment by abhijitxy** [comment]
Please assign me seve:)

**Comment by abhijitxy** [comment]
Resolved in PR https://github.com/tscircuit/builder/pull/97. Closing this issue
