### ISSUE TITLE
Add `schematicSnapshot(soup)` as a return from `getTestFixture`

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/tscircuit#308]

**Comment by imrishabh18** [comment]
@seveibar This function needs to be created inside `@tscircuit/log-soup` right?

**Comment by seveibar** [comment]
@imrishabh18 sorry for the delay, I would initially define it inside of [tscircuit/builder](https://github.com/tscircuit/builder) directly using circuit-to-png, we can break it out later. Best place is inside the `tests/fixtures` directory.

I don't think it'll live in logSoup to keep that module light, it could have a dedicated snapshot module maybe
