### ISSUE TITLE
Add support for pcb_keepouts

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#327]
- [x] Introduce `pcb_keepout` soup component [tscircuit/soup](https://github.com/tscircuit/soup)
- [x] Introduce `keepoutProps` in [tscircuit/props](https://github.com/tscircuit/props)
- [ ] Introduce `<keepout />` to [tscircuit/react-fiber](https://github.com/tscircuit/react-fiber)
- [ ] Create obstacles from keepout to avoid routing through it
- [ ] Add way to draw keepout inside of [tscircuit/pcb-viewer](https://github.com/tscircuit/pcb-viewer) (use a transparent crosshatch fill pattern)
- [ ] Add way to draw keeput inside [circuit-to-png](https://github.com/tscircuit/circuit-to-png)

---

A PCB keepout, also known as a keepout area or zone, is a designated region on a printed circuit board (PCB) where components, traces, or other design elements are not allowed to be placed. Keepouts are important design features used to:

1. Ensure clearance for mechanical components or enclosures
2. Prevent interference between components or circuits
3. Reserve space for specific purposes (e.g., mounting holes, heat sinks)
4. Comply with safety standards or regulatory requirements

Keepouts can be defined for various layers of the PCB, including:

- Component layers (top and bottom)
- Signal layers
- Power and ground planes

PCB design software typically allows designers to specify keepout areas using drawing tools. These areas are then respected by auto-routing algorithms and design rule checks.

**Comment by seveibar** [comment]
CC @andrii-balitskyi we discussed this today, also CC'ing @imrishabh18 if you're looking for a big issue not a bad one to pick up

**Comment by imrishabh18** [comment]
@seveibar I am confused here a bit, the `KeepoutBuilder` can be defined using this `defineNewComponent` function like for the `viaBuilder` here. Or, have it's own class defined?

![Screenshot 2024-08-10 at 5 05 23 PM](https://github.com/user-attachments/assets/41dbf8dc-1b11-45d6-9b94-d993632b69eb)

**Comment by seveibar** [comment]
If you can get `defineNewComponent` to work that's the "new" pattern!
