### ISSUE TITLE
Schematic Viewer missing pin lines

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#363]
![image](https://github.com/user-attachments/assets/aabaa8e0-939c-4440-8ebe-2c274856ca05)

**Comment by Abse2001** [comment]
I looked into the problem it seems that if you dont add the schPortArrangement prop on the bug/chip it will not draw the pin lines
![image](https://github.com/user-attachments/assets/3ff9173b-7d8f-4d13-81a4-9c4a1a9681eb)
![image](https://github.com/user-attachments/assets/4cee5550-4df5-410d-b323-4d0eeff9d618)

**Comment by seveibar** [comment]
oh weird, nice find

**Comment by Abse2001** [comment]
Is it not meant to be like that?

**Comment by seveibar** [comment]
Yea a chip should always have those red lines coming out connecting the ports, even if `schPortArrangement` isn't defined

**Comment by seveibar** [comment]
I'm not sure if the bug is in the [tscircuit/builder](https://github.com/tscircuit/builder) or [tscircuit/schematic-viewer](https://github.com/tscircuit/schematic-viewer)

**Comment by seveibar** [comment]
The way to determine what project the issue is in is probably to look at the circuit json/soup output and see if when `schPortArrangement` is defined if the soup changes and how. I think it's _probably_ a bug in [tscircuit/builder](https://github.com/tscircuit/builder)

**Comment by Abse2001** [comment]
will look more into this problem
