### ISSUE TITLE
Trace hints are broken in latest `tsci dev`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#365]
![image](https://github.com/user-attachments/assets/478429f1-7a0b-4688-bb96-cc4cf64de1b2)

CC @imrishabh18

**Comment by imrishabh18** [comment]
Can you share the circuit where you are seeing this error? I was just checking the version of `builder` in `cli`, It's not on the latest one, updating that maybe can fix this.

**Comment by seveibar** [comment]
Seeing it here: https://stackblitz.com/github/seveibar/seeed-board-demo?file=README.md
Repo: https://github.com/seveibar/seeed-board-demo

Here's a video, nothing happens when i click:


https://github.com/user-attachments/assets/b7499d30-eb6f-4807-9baf-7a68b54102d9
