### ISSUE TITLE
Small duplicate in Gerbers (probably due to bad units somewhere)

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#366]
![image](https://github.com/user-attachments/assets/272405fe-6a84-49a2-9e5a-a330f32b419d)

**Comment by ShiboSoftwareDev** [comment]
@seveibar I want this pcb layout you tested with is it uploaded somewhere?

**Comment by seveibar** [comment]
@ShiboSoftwareDev yes it's here!!!

https://github.com/seveibar/seeed-board-demo

Fwiw i believe this bug is in the "excellon drill" section of the builder codebase. Good luck!!!

**Comment by ShiboSoftwareDev** [comment]
Fixed in: [changed convertSoupToExcellonDrillCommands to use metric units](https://github.com/tscircuit/builder/pull/107).
