### ISSUE TITLE
Hackoberfest Preparation

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#443]
Hackoberfest is coming! To prepare, we're going to need to create some epics and good "getting started" work for new tscircuit contributors.

There are three main projects we'd like people to work on, which will need Epics and dedicated tutorials for new contributors:

- Our footprint library [tscircuit/footprinter](https://github.com/tscircuit/footprinter)
- Our 3d electronic components library [tscircuit/jscad-electronics](https://github.com/tscircuit/jscad-electronics)
- A yet-to-be-created sparkfun-clones library that clones sparkfun projects (they'll make great code examples for users!)

If you are interested in contributing to tscircuit for Hacktoberfest, subscribe to this issue's notifications!

Also check out our [daily dev streams](https://blog.tscircuit.com/s/devstreams) to understand how we work with our codebase!

Thanks to @imrishabh18 for the idea!

**Comment by RS-labhub** [comment]
waiting for it!

**Comment by vickywane** [comment]
Looking forward to this!

@seveibar can we have a list of "good-first" issues somewhere?

**Comment by imrishabh18** [comment]
Hey @vickywane! Thanks for the interest.

You can refer to this blog post, it has a lot of info about the issues, with the tutorials as well.

https://blog.tscircuit.com/p/build-electronics-with-typescript
