### ISSUE TITLE
Autocloud Autorouting has some kind of inversion over either the X or Y axis

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#479]
![Image](https://github.com/user-attachments/assets/7a4182b1-13d4-4ba1-acbf-6a322102782c)

**Comment by seveibar** [comment]
It doesn't look like this is caused by the registry api or freerouting cluster, we had some internal snapshot testing [here](https://github.com/tscircuit/registry-api/pull/35) that demonstrates that the api doesn't cause an inversion if you just send it circuit json

**Comment by seveibar** [comment]
CC @imrishabh18 this is where i'm tracking the inversion issue. I'm a bit confused where it could be happening because the registry api test seems to imply it's NOT happening in any of the cloud stuff (dsn-converter, freerouting or registry-api). More testing needed...

**Comment by seveibar** [comment]
It also seems to work for me for simple examples



Could it be an issue with something like plated holes? I'm not sure... the wifi on this plane is so bad i'm spending a lot of time waiting for things to load 😅

**Comment by seveibar** [comment]
Just confirmed it only seems to invert plated holes. I have images but can't upload them over the plane wifi. Here's a simple example reproducing the inversion:

```tsx
export default () => (
  <board width="10mm" height="10mm" autorouter="auto-cloud">
    <resistor
      resistance="1k"
      footprint="axial"
      name="R1"
      schX={3}
      pcbX={3}
      pcbY={3}
      pcbRotation="90deg"
    />
    
    <capacitor
      capacitance="1000pF"
      footprint="0402"
      name="C1"
      schX={-3}
      pcbX={-3}
    />
    <trace from=".R1 > .pin1" to=".C1 > .pin1" />
  </board>
)
```

**Comment by imrishabh18** [comment]
@seveibar The dsn file conversion from the circuit json for the `plated_hole` is the issue. The source trace is not getting converted to the correct `net` in dsn

**Comment by imrishabh18** [comment]
@seveibar  Closing this as this is fixed now

![Image](https://github.com/user-attachments/assets/64312178-e160-4dd1-a908-44e5dc339b77)
