### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by kainpets** [tscircuit/tscircuit#94]
Running setup following README returns the attached error.

Might be I'm doing something wrong but looks to me like the link to the npm registry isn't right? 
@tsci:registry=https://registry-api.tscircuit.com/npm

<img width="960" alt="Screenshot 2024-04-25 at 03 44 00" src="https://github.com/tscircuit/tscircuit/assets/41388251/73948336-0b6f-49aa-a454-f780d4fe54ad">

<img width="960" alt="Screenshot 2024-04-25 at 03 43 43" src="https://github.com/tscircuit/tscircuit/assets/41388251/49bafacd-5721-477c-9bcb-1d339496aae5">
  
<img width="960" alt="Screenshot 2024-04-25 at 03 53 37" src="https://github.com/tscircuit/tscircuit/assets/41388251/b0b54e0b-7b33-435a-8e12-cde469cda7d4">

**Comment by seveibar** [comment]
Taking a look!

**Comment by seveibar** [comment]
I think this might have something to do with your globally installed `tsx` version, can you do `npx tsx --version`?

`npm install -g tsx@latest` might resolve it- right now we're not bundling the `tsx` dependency, we probably should

**Comment by seveibar** [comment]
Hmm actually I think it might be do to the default package.json created by `npm`, working on a reproduction...

**Comment by seveibar** [comment]
Can you paste your `package.json` file?

**Comment by kainpets** [comment]
I have the latest version of tsx installed globally
<img width="1920" alt="Screenshot 2024-04-25 at 10 12 01" src="https://github.com/tscircuit/tscircuit/assets/41388251/893ab867-fcc9-4f64-b721-d484ddc4aeaa">

**Comment by seveibar** [comment]
I think you need to add "type": "module" to the package.json, I've updated the latest version of `tsci init` to add it automatically

**Comment by kainpets** [comment]
Yep, that worked, thank you! Should've probably realised I had to run `tsci init`. 😅

**Comment by seveibar** [comment]
thanks for trying it out!!!!!
